name: Auto Release

on:
  push:
    branches:
      - version-core
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Check if Git is installed
        run: git --version
    
      - name: Check if directory is a Git repository
        run: git rev-parse --is-inside-work-tree
        id: check_git_repo
        continue-on-error: true

      - name: Configure
        run: ./configure && cmake --version
    
      - name: Check Commit Message
        id: check_commit_message
        run: echo ::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})

      - name: Trigger Release
        if: startsWith(steps.check_commit_message.outputs.message, '[release]')
        run: |
          echo "test released..."
